version: '3'

services:
  python:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        IMAGE_NAME: ${IMAGE_NAME}
        REQUIREMENTS_PATH: ${REQUIREMENTS_PATH}
    volumes:
      - ${VOLUME}:/${VOLUME}
    tty: true
    stdin_open: true
